# Generated by Django 3.2.4 on 2021-06-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='lname',
        ),
    ]
